# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true
    includePrerelease: true
    
- script: |
    yarn install
  displayName: 'Install'

- script: |
    yarn build
  displayName: 'Build'

- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/build' 
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive build files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'TeachmeFeF'
    publishLocation: 'Container'
  displayName: 'Publish artifact'
